name: organizer_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  grpc: ^3.0.2
  protobuf: ^2.1.0
  google_fonts: ^3.0.1
  responsive_framework: ^0.2.0
  get: ^4.6.5
  getwidget: ^3.0.1
  flex_color_scheme: ^5.1.0
  intl_phone_field: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pinput: ^2.2.11
  uuid: ^3.0.6
  connectivity_plus: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
